-- Postgres Schema for Project: gapura-irrs
-- Extracted via Supabase introspection
-- Generated on: 2026-02-13

-- =============================================
-- 1. Core Users & Auth
-- =============================================

-- TABLE: users
-- Extends auth.users or usage as internal user registry
CREATE TABLE IF NOT EXISTS public.users (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    email text NOT NULL,
    password text NOT NULL,
    full_name text NOT NULL,
    role text, -- 'super_admin', 'analyst', 'user'
    status text,
    nik text,
    phone text,
    station_id uuid,
    unit_id uuid,
    position_id uuid,
    department text,
    division text DEFAULT 'GENERAL'::text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- =============================================
-- 2. Master Data (Static / Reference)
-- =============================================

-- TABLE: stations
CREATE TABLE IF NOT EXISTS public.stations (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    code text NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- TABLE: units
CREATE TABLE IF NOT EXISTS public.units (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL,
    description text,
    created_at timestamp with time zone DEFAULT now()
);

-- TABLE: positions
CREATE TABLE IF NOT EXISTS public.positions (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL,
    level integer NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);

-- TABLE: incident_types
CREATE TABLE IF NOT EXISTS public.incident_types (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL,
    default_severity text,
    created_at timestamp with time zone DEFAULT now()
);

-- TABLE: locations
CREATE TABLE IF NOT EXISTS public.locations (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    station_id uuid, -- Link to stations(id)
    name text NOT NULL,
    area text,
    created_at timestamp with time zone DEFAULT now()
);

-- =============================================
-- 3. Operational Data (Reports & Incidents)
-- =============================================

-- TABLE: reports
CREATE TABLE IF NOT EXISTS public.reports (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    reference_number text,
    title text NOT NULL,
    description text NOT NULL,
    
    -- Status & Workflow
    status text DEFAULT 'OPEN'::text,
    priority text DEFAULT 'low'::text,
    severity text,
    
    -- Dimensions
    branch text,
    station_code text,
    airline text,
    airline_type text,
    flight_number text,
    aircraft_reg text,
    route text,
    area text,
    area_category text,
    specific_location text,
    
    -- Categorization
    category text DEFAULT 'OTHER'::text,
    main_category text,
    sub_category text,
    is_flight_related boolean DEFAULT false,
    is_gse_related boolean DEFAULT false,
    gse_number text,
    
    -- Dates
    incident_date date,
    incident_time time without time zone,
    event_date timestamp with time zone,
    form_submitted_at timestamp with time zone,
    form_completed_at timestamp with time zone,
    sla_deadline timestamp with time zone,
    
    -- Actions & Notes
    immediate_action text,
    report_content text,
    root_cause text,
    action_taken text,
    investigator_notes text,
    manager_notes text,
    kps_remarks text,
    partner_response_notes text,
    validation_notes text,
    
    -- People / Relations
    user_id uuid, -- Reporter
    reporter_name text,
    reporter_email text,
    reporting_branch text,
    assigned_to uuid,
    pic text,
    
    -- Workflow Users
    acknowledged_by uuid,
    resolved_by uuid,
    validated_by uuid,
    
    -- Timestamps
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    started_at timestamp with time zone,
    acknowledged_at timestamp with time zone,
    resolved_at timestamp with time zone,
    closed_at timestamp with time zone,
    validated_at timestamp with time zone,

    -- System / Meta
    department text,
    target_division text DEFAULT 'OS'::text,
    hub text,
    week_in_month integer,
    csv_id integer,
    
    -- Files / JSON
    evidence_url text,
    evidence_urls text[],
    partner_evidence_urls text[],
    evidence_meta jsonb DEFAULT '[]'::jsonb,
    
    -- Foreign Keys (Logical)
    station_id uuid,
    unit_id uuid,
    location_id uuid,
    incident_type_id uuid,
    
    -- Search
    fts tsvector GENERATED ALWAYS AS (to_tsvector('english', coalesce(title, '') || ' ' || coalesce(description, ''))) STORED
);

-- TABLE: report_comments
CREATE TABLE IF NOT EXISTS public.report_comments (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    report_id uuid NOT NULL, -- Logical FK to reports(id) (Note: reports.id is bigint, check type match)
    user_id uuid NOT NULL,
    content text NOT NULL,
    attachments text[],
    is_system_message boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

-- TABLE: report_logs
CREATE TABLE IF NOT EXISTS public.report_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    report_id uuid, 
    user_id uuid,
    action text NOT NULL,
    note text,
    previous_status text,
    new_status text,
    created_at timestamp with time zone DEFAULT now()
);

-- TABLE: audit_logs
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    actor_id uuid,
    action text NOT NULL,
    entity_type text NOT NULL,
    entity_id text NOT NULL,
    old_value jsonb,
    new_value jsonb,
    ip_address text,
    user_agent text,
    created_at timestamp with time zone DEFAULT now()
);

-- =============================================
-- 4. Dashboard & Analytics
-- =============================================

-- TABLE: custom_dashboards
CREATE TABLE IF NOT EXISTS public.custom_dashboards (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    name text NOT NULL,
    description text,
    slug text NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    is_public boolean DEFAULT true,
    created_by uuid,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- TABLE: dashboard_charts
CREATE TABLE IF NOT EXISTS public.dashboard_charts (
    id uuid DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    dashboard_id uuid, -- FK to custom_dashboards(id)
    title text NOT NULL,
    chart_type text NOT NULL, -- 'bar', 'line', 'pie', 'heatmap', etc.
    data_field text NOT NULL,
    page_name text DEFAULT 'Ringkasan Umum'::text,
    position integer DEFAULT 0,
    width text DEFAULT 'half'::text,
    config jsonb DEFAULT '{}'::jsonb,
    query_config jsonb,
    visualization_config jsonb,
    layout jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- =============================================
-- 5. Indexes
-- =============================================

CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);
CREATE INDEX IF NOT EXISTS idx_reports_status ON public.reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON public.reports(created_at);
CREATE INDEX IF NOT EXISTS idx_reports_branch ON public.reports(branch);
CREATE INDEX IF NOT EXISTS idx_reports_airline ON public.reports(airline);
CREATE INDEX IF NOT EXISTS idx_custom_dashboards_slug ON public.custom_dashboards(slug);
CREATE INDEX IF NOT EXISTS idx_dashboard_charts_dashboard_id ON public.dashboard_charts(dashboard_id);

-- =============================================
-- 6. Row Level Security (RLS)
-- =============================================

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.custom_dashboards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dashboard_charts ENABLE ROW LEVEL SECURITY;

-- Note: Policies need to be added manually based on specific business logic.
