export const AIRLINES = [
    { code: 'GA', name: 'Garuda Indonesia' },
    { code: 'QG', name: 'Citilink' },
    { code: 'JT', name: 'Lion Air' },
    { code: 'ID', name: 'Batik Air' },
    { code: 'IW', name: 'Wings Air' },
    { code: 'IU', name: 'Super Air Jet' },
    { code: 'QZ', name: 'AirAsia Indonesia' },
    { code: 'SJ', name: 'Sriwijaya Air' },
    { code: 'IN', name: 'NAM Air' },
    { code: 'IP', name: 'Pelita Air' },
    { code: '8B', name: 'TransNusa' },
    { code: 'SI', name: 'Susi Air' },
    { code: 'IL', name: 'Trigana Air' },
    { code: 'SQ', name: 'Singapore Airlines' },
    { code: 'TR', name: 'Scoot' },
    { code: 'MH', name: 'Malaysia Airlines' },
    { code: 'QR', name: 'Qatar Airways' },
    { code: 'EK', name: 'Emirates' },
    { code: 'EY', name: 'Etihad Airways' },
    { code: 'TK', name: 'Turkish Airlines' },
    { code: 'JL', name: 'Japan Airlines' },
    { code: 'NH', name: 'All Nippon Airways (ANA)' },
    { code: 'CZ', name: 'China Southern Airlines' },
    { code: 'MU', name: 'China Eastern Airlines' },
    { code: 'CA', name: 'Air China' },
    { code: 'CX', name: 'Cathay Pacific' },
    { code: 'BR', name: 'EVA Air' },
    { code: 'CI', name: 'China Airlines' },
    { code: 'KE', name: 'Korean Air' },
    { code: 'OZ', name: 'Asiana Airlines' },
    { code: 'QF', name: 'Qantas' },
    { code: 'JQ', name: 'Jetstar' },
    { code: 'KL', name: 'KLM Royal Dutch Airlines' },
    { code: 'SV', name: 'Saudia' },

    { code: 'VN', name: 'Vietnam Airlines' },
    { code: 'TG', name: 'Thai Airways' },
    { code: 'PR', name: 'Philippine Airlines' },
    { code: 'BI', name: 'Royal Brunei Airlines' },
    { code: 'OTHER', name: 'Other / Lainnya' }
].sort((a, b) => a.name.localeCompare(b.name));
